apiVersion: v1
kind: Service
metadata: 
  name: mynginx
  labels:
    app: dev
    name: mynginx
spec:
  type: NodePort
  selector:
    app: dev
    name: mynginx
  ports:
  - nodePort: 30001 
    port: 80
    protocol: TCP
    targetPort: 80