apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mynginx-rs
  labels:
    app: mynginx-rs
    type: dev
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: mynginx-rs
      type: dev
  template:
    metadata:
      name: mynginx-rs
      labels:
        app: mynginx-rs
        type: dev
    spec:
      containers:
      - image: nginx
        name: mynginx-rs
        ports:
          containerPort: 80
          protocol: TCP

