apiVersion: v1
kind: ReplicationController
metadata: 
  name: mynginx
  labels:
    app: dev
    name: mynginx
spec: 
  replicas: 2
  selector: 
    app: dev
    name: mynginx  
  template:
    metadata:
      name: contnginx
      labels: 
        app: dev
        name: mynginx
    spec:
      containers: 
      - image: nginx
        name: mynginx
        ports:
        - containerPort: 80
          name: mynginx
          protocol: TCP
